testing doc

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -193,6 +193,26 @@ references:
         chmod -x gradlew
         ./gradlew build -x test
 
+  start_test_project_agent: &start_test_project_agent
+        - run:
+          name: Start Agent and Wait for agent to register
+          command: |
+            set -x
+            docker-compose up -d
+            trap 'kill $(jobs -p)' EXIT
+            attempt_counter=0
+            max_attempts=45
+            mkdir -p build/reports/agent
+            docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
+            until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
+              if [ ${attempt_counter} -eq ${max_attempts} ]; then
+                echo "Agent failed to register. Terminating..."
+                exit 1
+              fi
+              attempt_counter=$(($attempt_counter+1))
+              sleep 1
+            done
+
 
 
 
@@ -245,8 +265,12 @@ jobs:
     <<: *android_config
     docker:
       - image: circleci/android:api-29
+        auth:
+          username: $DOCKER_USER
+          password: $DOCKER_PASSWORD
     steps:
       - checkout
       - *install_jdk_11
       - *update_gradlew_code
+      - *start_test_project_agent
       - *run_testing
